---
name: "Terraform Plan - tflabs002"

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

env:
    TF_IN_AUTOMATION: "true"
    TF_INPUT: "false"
    TF_VERSION: "1.14.1"

concurrency:
    group: tf-plan-${{ github.ref }}
    cancel-in-progress: false

defaults:
    run:
        shell: bash

jobs:
    tf_plan:
        name: Terraform Plan
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./infra/terraform

        steps:
            - name: "Checkout"
              id: checkout-code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: "Terraform - Setup"
              id: terraform-setup
              uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
              with:
                terraform_version: ${{ env.TF_VERSION }}

            - name: "Terraform Format"
              id: terraform-format
              run: |
                set -euo pipefail
                terraform fmt -check -recursive
              env:
                TF_LOG: "${{ runner.debug == '1' || ''}}"

            - name: "Azure Login"
              id: azure-login
              uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Terraform Init
              id: terraform-init
              run: |
                set -euo pipefail
                ls -al
                terraform init
              env:
                TF_LOG: "${{ runner.debug == '1' || ''}}"

            - name: Terraform Version
              id: terraform-version
              run: |
                set -euo pipefail
                terraform version
              env:
                TF_LOG: "${{ runner.debug == '1' || ''}}"

            - name: Terraform Validate
              id: terraform-validate
              run: |
                set -euo pipefail
                terraform validate
              env:
                TF_LOG: "${{ runner.debug == '1' || ''}}"

            - name: Terraform Plan
              id: terraform-plan
              run: |
                set -euo pipefail
                terraform plan -var-file=./config/terraform.tfvars
              env:
                TF_LOG: "${{ runner.debug == '1' || ''}}"
                

            
